Libraries
EVOLVED-5G/SDK-CLI pull request #111
Opened 2022-10-17 17:26 UTC by AlexJoom

New SDK Class CAPIFExposerConnector that allows an exposer to register to CAPIF and publish services

2022-10-20 11:47 UTC, AlexJoom commented
I updated the  CAPIFInvokerConnector to use a config file instead.

You can squash and merge and the set the following as the commit message:

Addition 3 new SDK Libraries classes 
* **CAPIFInvokerConnector** a low level class, that is used by the evolved-5G CLI in order to register NetApps to CAPIF
* **CAPIFExposerConnector** a low level class, that allows an Exposer (like the NEF emulator) to register to CAPIF
* **ServiceDiscoverer** allows NetApp developer to connect to CAPIF in order to discover services

Addition of a new CLI command 
* **evolved5g** register-and-onboard-to-capif"

2022-10-20 14:50 UTC, rimarala requested changes
The examples you are providing are very nice and easy to follow but we suggest changing some paths, e.g., "/home/alex/Projects/test_nef_certificate_folder/service_api_description.json" to "The_path_to_service_api_description_json", which could be more descriptive for developers.

2022-10-21 10:47 UTC, pencinarsanz-atos approved these changes

2022-10-21 10:58 UTC, rimarala approved these changes

2022-10-24 08:38 UTC, merged