Pypi task
EVOLVED-5G/SDK-CLI pull request #37
Opened 2021-11-08 10:45 UTC by pencinarsanz-atos

2021-11-08 11:45 UTC, skolome reviewed
To fully update the version of the application, there are actually three files to change. setup.py, setup.cfg & __init__py in the code folder. Better option is to use the "bump2version" module already installed from the requirements_dev.txt . It updates the files and pushes to remote repository.

usage example: bump2version --new-version 0.5.6 minor

2021-12-16 17:35 UTC, pencinarsanz-atos commented
@skolome I have modified this branch. In the end I'm going to work with a github workflow and not use bump2version. So the setup.cfg and __init__.py files are not needed anymore. When you look at it I will test it in master.

2022-01-26 08:42 UTC, rimarala requested changes
Please change version in file setup.py to 0.6.0.

2022-01-26 09:10 UTC, rimarala approved these changes

2022-01-26 09:11 UTC, merged